name: Ricard Gascons
markdown: redcarpet
highlighter: pygments
github: https://www.github.com/zakum42
about: I am a Computer Science student from Barcelona. I usually program in Python, tinker with C++ and currently learning ML.
urls:
    - text: github
      url: https://github.com/zakum42
baseurl: ''
url: http://rgascons.cc/
gems:
  - jekyll-feed